# Site settings
title: Data for Society
description: Research organization advancing data science for social good
baseurl: "/data-for-society"
url: "https://uchicago-pol-methods.github.io"
author:
  name: Data for Society
  email: dataforsociety@uchicago.edu

plugins:
  - jekyll-sitemap

# Build settings
markdown: kramdown

sass:
  load_paths:
    - css